components:
  schemas: {}
  securitySchemes: {}
info:
  title: CRM Full API Test
  version: eba5f616-4bc3-4149-8b7b-fa201669add7
openapi: 3.0.0
paths:
  /attendance/123/0:
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Mark Attendance
  /attendance/report:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get Attendance Report
  /auth/login:
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Login User
  /auth/register:
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Register User
  /documents/123/receipt:
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get Documents
  /export/admins:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Export Admins
  /export/payments:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Export All Receipts
  /export/students:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Export Students
  /export/teachers:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Export Teachers
  /reminders:
    put:
      description: ''
      responses:
        '200':
          description: OK
      summary: Update Reminder
  /reminders/morning:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get Reminder
  /schedules:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get All Schedules
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Create Schedule
  /schedules/123:
    delete:
      description: ''
      responses:
        '200':
          description: OK
      summary: Delete Schedule
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get Schedule by ID
    put:
      description: ''
      responses:
        '200':
          description: OK
      summary: Update Schedule
  /schedules/123/copy:
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Copy Schedule
  /schedules/123/slots:
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Add Slot
  /schedules/123/slots/0:
    delete:
      description: ''
      responses:
        '200':
          description: OK
      summary: Delete Slot
    put:
      description: ''
      responses:
        '200':
          description: OK
      summary: Update Slot
  /schedules/123/slots/0/assign:
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Assign Student to Slot
  /students:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get All Students
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Create Student
  /students/123:
    delete:
      description: ''
      responses:
        '200':
          description: OK
      summary: Delete Student
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get Student by ID
    put:
      description: ''
      responses:
        '200':
          description: OK
      summary: Update Student
  /students/123/receipts:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get Receipts
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Upload Receipt
  /tasks:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get All Tasks
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Create Task
  /tasks/123:
    delete:
      description: ''
      responses:
        '200':
          description: OK
      summary: Delete Task
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get Task by ID
    put:
      description: ''
      responses:
        '200':
          description: OK
      summary: Update Task
  /tasks/123/complete:
    patch:
      description: ''
      responses:
        '200':
          description: OK
      summary: Mark Task Complete
  /users:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get All Users
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Create User
  /users/123:
    delete:
      description: ''
      responses:
        '200':
          description: OK
      summary: Delete User
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get User by ID
    put:
      description: ''
      responses:
        '200':
          description: OK
      summary: Update User
  /whatsapp-logs:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get Logs
  /whatsapp-logs/1234567890:
    get:
      description: ''
      responses:
        '200':
          description: OK
      summary: Get Logs by Phone
  /whatsapp/send:
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Send Message
  /whatsapp/send-bulk:
    post:
      description: ''
      responses:
        '200':
          description: OK
      summary: Send Bulk Messages
security: []